Started docker

diff --git a/install b/install
--- a/install
+++ b/install
@@ -18,6 +18,8 @@ pacman -Syu --noconfirm || die "Could not update dist"
 echo "Ensuring docker is installed"
 pacman -S --noconfirm --needed docker docker-compose docker-buildx git pigz criu || die "Could not install docker"
 
+systemctl enable --now docker.socket || die "Could not enable docker timer"
+systemctl enable --now docker || die "Could not enable docker.service"
 
 echo "Installing auto-update service"
 {
