Update install script to include pkgstats
Added pkgstats to the installation process and enabled its service.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -19,7 +19,7 @@ echo "Explicit RUNC version"
 curl https://archive.archlinux.org/packages/r/runc/runc-1.3.2-1-x86_64.pkg.tar.zst -o runc-1.3.2-1-x86_64.pkg.tar.zst && pacman -U --noconfirm ./runc-1.3.2-1-x86_64.pkg.tar.zst
 
 echo "Ensuring packages is installed"
-pacman -S --noconfirm --needed docker docker-compose docker-buildx git pigz criu firewalld || die "Could not install docker"
+pacman -S --noconfirm --needed docker docker-compose docker-buildx git pigz criu firewalld pkgstats || die "Could not install docker"
 
 echo "Configuring Docker Mirror"
 
@@ -37,6 +37,9 @@ fi
 echo "Enabling Docker"
 systemctl enable --now docker.socket || die "Could not enable docker timer"
 systemctl enable --now docker || die "Could not enable docker.service"
+
+echo "Enabling pkgstats"
+sudo systemctl enable --now pkgstats.timer
 
 echo "Enabling firewalld"
 systemctl enable --now firewalld
