Enable QEMU Guest Agent in install script
Added commands to enable QEMU Guest Agent service.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -65,6 +65,9 @@ sudo systemctl start pkgstats.timer
 echo "Enabling firewalld"
 systemctl enable --now firewalld
 
+echo "Enable QEMU Guest Agent"
+systemctl enable --now qemu-ga.service || die "Could not enable qemu-ga.service"
+
 echo "Installing auto-update service"
 {
   echo "[Unit]"
