Install and configure Reflector in the install script
Added reflector package installation and configuration.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -40,7 +40,19 @@ pacman -Syu --noconfirm || die "Could not update dist"
 #curl https://archive.archlinux.org/packages/r/runc/runc-1.3.2-1-x86_64.pkg.tar.zst -o runc-1.3.2-1-x86_64.pkg.tar.zst && pacman -U --noconfirm ./runc-1.3.2-1-x86_64.pkg.tar.zst
 
 echo "Ensuring packages is installed"
-pacman -S --noconfirm --needed docker docker-compose docker-buildx git pigz criu firewalld pkgstats || die "Could not install docker"
+pacman -S --noconfirm --needed docker docker-compose docker-buildx git pigz criu firewalld pkgstats reflector || die "Could not install docker"
+
+
+echo "Configuring Reflector"
+cat << EOF >> /etc/pacman.confe mirrorlist will be saved (--save).
+--save /etc/pacman.d/mirrorlist
+--protocol https
+--latest 10
+--sort rate
+EOF
+
+systemctl enable --now reflector.time
+systemctl start reflector.timer
 
 echo "Configuring Docker Mirror"
 
