workaround for runc security

diff --git a/install b/install
--- a/install
+++ b/install
@@ -10,6 +10,7 @@ die() {
 echo "Updating pacman.conf"
 
 sed -i "s|Include = /etc/pacman.d/mirrorlist|Server = https://pacman.markridgwell.com/repo/archlinux/\$repo/os/\$arch|" /etc/pacman.conf || die "Could not update pacman.conf"
+sed -i "s|IgnorePkg   =|IgnorePkg   = runc|" /etc/pacman.conf || die "Could not update pacman.conf"
 
 
 echo "Updating Packages"
@@ -17,6 +18,8 @@ pacman -Syu --noconfirm || die "Could not update dist"
 
 echo "Ensuring packages is installed"
 pacman -S --noconfirm --needed docker docker-compose docker-buildx git pigz criu firewalld || die "Could not install docker"
+
+curl https://archive.archlinux.org/packages/r/runc/runc-1.3.2-1-x86_64.pkg.tar.zst -o runc-1.3.2-1-x86_64.pkg.tar.zst && pacman -U ./runc-1.3.2-1-x86_64.pkg.tar.zst
 
 echo "Enabling Docker"
 systemctl enable --now docker.socket || die "Could not enable docker timer"
