Add qemu-guest-agent to package installation

diff --git a/install b/install
--- a/install
+++ b/install
@@ -40,7 +40,7 @@ pacman -Syu --noconfirm || die "Could not update dist"
 #curl https://archive.archlinux.org/packages/r/runc/runc-1.3.2-1-x86_64.pkg.tar.zst -o runc-1.3.2-1-x86_64.pkg.tar.zst && pacman -U --noconfirm ./runc-1.3.2-1-x86_64.pkg.tar.zst
 
 echo "Ensuring packages is installed"
-pacman -S --noconfirm --needed docker docker-compose docker-buildx git pigz criu firewalld pkgstats || die "Could not install docker"
+pacman -S --noconfirm --needed docker docker-compose docker-buildx git pigz criu firewalld pkgstats qemu-guest-agent || die "Could not install docker"
 
 echo "Configuring Docker Mirror"
 
