Enabling firewall

diff --git a/install b/install
--- a/install
+++ b/install
@@ -15,11 +15,14 @@ sed -i "s|Include = /etc/pacman.d/mirrorlist|Server = https://pacman.markridgwel
 echo "Updating Packages"
 pacman -Syu --noconfirm || die "Could not update dist"
 
-echo "Ensuring docker is installed"
-pacman -S --noconfirm --needed docker docker-compose docker-buildx git pigz criu || die "Could not install docker"
+echo "Ensuring packages is installed"
+pacman -S --noconfirm --needed docker docker-compose docker-buildx git pigz criu firewalld || die "Could not install docker"
 
+echo "Enabling Docker"
 systemctl enable --now docker.socket || die "Could not enable docker timer"
 systemctl enable --now docker || die "Could not enable docker.service"
+
+echo "Enabling firewalld"
 
 echo "Installing auto-update service"
 {
